server:
  port: 9988
spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.51:27017/cyberArchive
  datasource:
    url: jdbc:mysql://47.93.25.57:3306/thams?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#spring:
#  data:
#    mongodb:
#      uri: mongodb://192.168.0.51:27017/cyberArchive
logging:
  level:
    cn:
      zh:
        zhbackend:
          canseeguan:
            dao: debug
mybatis:
  config-location: classpath:mybatis-config.xml

##pdf文件根目录
pdfRootPath: /Users/mac/Desktop

