server:
  port: 9988
spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.51:27017/cyberArchive
      connections-per-host: 20
#spring:
#  data:
#    mongodb:
#      uri: mongodb://192.168.0.51:27017/cyberArchive
